// Pedir lista de clientes
export const REQUEST_CLIENTE_LISTA = "REQUEST_CLIENTE_LISTA";
export const SUCCESS_CLIENTE_LISTA = "SUCCESS_CLIENTE_LISTA";
export const FAIL_CLIENTE_LISTA = "FAIL_CLIENTE_LISTA";
export const RESET_CLIENTE_LISTA = "RESET_CLIENTE_LISTA";
