// Pedir lista de productos
export const REQUEST_PRODUCTO_LISTA = "REQUEST_PRODUCTO_LISTA";
export const SUCCESS_PRODUCTO_LISTA = "SUCCESS_PRODUCTO_LISTA";
export const FAIL_PRODUCTO_LISTA = "FAIL_PRODUCTO_LISTA";
export const RESET_PRODUCTO_LISTA = "RESET_PRODUCTO_LISTA";
