// Pedir lista de rutas
export const REQUEST_RUTA_LISTA = "REQUEST_RUTA_LISTA";
export const SUCCESS_RUTA_LISTA = "SUCCESS_RUTA_LISTA";
export const FAIL_RUTA_LISTA = "FAIL_RUTA_LISTA";
export const RESET_RUTA_LISTA = "RESET_RUTA_LISTA";

// Pedir un solo ruta
export const REQUEST_RUTA_DETALLES = "REQUEST_RUTA_DETALLES";
export const SUCCESS_RUTA_DETALLES = "SUCCESS_RUTA_DETALLES";
export const FAIL_RUTA_DETALLES = "FAIL_RUTA_DETALLES";
export const RESET_RUTA_DETALLES = "RESET_RUTA_DETALLES";

// Actualizar un ruta
export const REQUEST_RUTA_ACTUALIZAR = "REQUEST_RUTA_ACTUALIZAR";
export const SUCCESS_RUTA_ACTUALIZAR = "SUCCESS_RUTA_ACTUALIZAR";
export const FAIL_RUTA_ACTUALIZAR = "FAIL_RUTA_ACTUALIZAR";
export const RESET_RUTA_ACTUALIZAR = "RESET_RUTA_ACTUALIZAR";

// Registrar un nuevo ruta
export const REQUEST_RUTA_REGISTRAR = "REQUEST_RUTA_REGISTRAR";
export const SUCCESS_RUTA_REGISTRAR = "SUCCESS_RUTA_REGISTRAR";
export const FAIL_RUTA_REGISTRAR = "FAIL_RUTA_REGISTRAR";
export const RESET_RUTA_REGISTRAR = "RESET_RUTA_REGISTRAR";

// Borrar un rita
export const REQUEST_RUTA_BORRAR = "REQUEST_RUTA_BORRAR";
export const SUCCESS_RUTA_BORRAR = "SUCCESS_RUTA_BORRAR";
export const FAIL_RUTA_BORRAR = "FAIL_RUTA_BORRAR";
export const RESET_RUTA_BORRAR = "RESET_RUTA_BORRAR";
