// Pedir lista de rutas
export const REQUEST_RUTA_LISTA = "REQUEST_RUTA_LISTA";
export const SUCCESS_RUTA_LISTA = "SUCCESS_RUTA_LISTA";
export const FAIL_RUTA_LISTA = "FAIL_RUTA_LISTA";
export const RESET_RUTA_LISTA = "RESET_RUTA_LISTA";

// Pedir un solo ruta
export const REQUEST_RUTA_DETALLES = "REQUEST_RUTA_DETALLES";
export const SUCCESS_RUTA_DETALLES = "SUCCESS_RUTA_DETALLES";
export const FAIL_RUTA_DETALLES = "FAIL_RUTA_DETALLES";
export const RESET_RUTA_DETALLES = "RESET_RUTA_DETALLES";

// Actualizar un ruta
export const REQUEST_RUTA_ACTUALIZAR = "REQUEST_RUTA_ACTUALIZAR";
export const SUCCESS_RUTA_ACTUALIZAR = "SUCCESS_RUTA_ACTUALIZAR";
export const FAIL_RUTA_ACTUALIZAR = "FAIL_RUTA_ACTUALIZAR";
export const RESET_RUTA_ACTUALIZAR = "RESET_RUTA_ACTUALIZAR";

// Registrar una nueva ruta
export const REQUEST_RUTA_REGISTRAR = "REQUEST_RUTA_REGISTRAR";
export const SUCCESS_RUTA_REGISTRAR = "SUCCESS_RUTA_REGISTRAR";
export const FAIL_RUTA_REGISTRAR = "FAIL_RUTA_REGISTRAR";
export const RESET_RUTA_REGISTRAR = "RESET_RUTA_REGISTRAR";

// Borrar un ruta
export const REQUEST_RUTA_BORRAR = "REQUEST_RUTA_BORRAR";
export const SUCCESS_RUTA_BORRAR = "SUCCESS_RUTA_BORRAR";
export const FAIL_RUTA_BORRAR = "FAIL_RUTA_BORRAR";
export const RESET_RUTA_BORRAR = "RESET_RUTA_BORRAR";

// Pedir lista de rutas dias
export const REQUEST_RUTA_DIA_LISTA = "REQUEST_RUTA_DIA_LISTA";
export const SUCCESS_RUTA_DIA_LISTA = "SUCCESS_RUTA_DIA_LISTA";
export const FAIL_RUTA_DIA_LISTA = "FAIL_RUTA_DIA_LISTA";
export const RESET_RUTA_DIA_LISTA = "RESET_RUTA_DIA_LISTA";

// Pedir ruta dias
export const REQUEST_RUTA_DIA_DETALLES = "REQUEST_RUTA_DIA_DETALLES";
export const SUCCESS_RUTA_DIA_DETALLES = "SUCCESS_RUTA_DIA_DETALLES";
export const FAIL_RUTA_DIA_DETALLES = "FAIL_RUTA_DIA_DETALLES";
export const RESET_RUTA_DIA_DETALLES = "RESET_RUTA_DIA_DETALLES";

// Pedir clientes de ruta dia
export const REQUEST_RUTA_DIA_CLIENTES = "REQUEST_RUTA_DIA_CLIENTES";
export const SUCCESS_RUTA_DIA_CLIENTES = "SUCCESS_RUTA_DIA_CLIENTES";
export const FAIL_RUTA_DIA_CLIENTES = "FAIL_RUTA_DIA_CLIENTES";
export const RESET_RUTA_DIA_CLIENTES = "RESET_RUTA_DIA_CLIENTES";

// Actualizar un ruta dia
export const REQUEST_RUTA_DIA_ACTUALIZAR = "REQUEST_RUTA_DIA_ACTUALIZAR";
export const SUCCESS_RUTA_DIA_ACTUALIZAR = "SUCCESS_RUTA_DIA_ACTUALIZAR";
export const FAIL_RUTA_DIA_ACTUALIZAR = "FAIL_RUTA_DIA_ACTUALIZAR";
export const RESET_RUTA_DIA_ACTUALIZAR = "RESET_RUTA_DIA_ACTUALIZAR";
