// Pedir lista de usuarios
export const REQUEST_USUARIO_LISTA = "REQUEST_USUARIO_LISTA";
export const SUCCESS_USUARIO_LISTA = "SUCCESS_USUARIO_LISTA";
export const FAIL_USUARIO_LISTA = "FAIL_USUARIO_LISTA";
export const RESET_USUARIO_LISTA = "RESET_USUARIO_LISTA";
